name: golang CI-dev

on: push

jobs:
  CI-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sls-go-middleware
        uses: actions/checkout@v2

      - name: Print dir
        run: ls

      - name: Update ubuntu
        run: sudo apt-get -qq update

      - name: Install curl, jq, make, zip, ping, net-tools
        run:  sudo apt-get -qq -y install curl jq build-essential zip iputils-ping net-tools

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'

      - name: Install Go modules, gotest and golangci-lint
        run: go mod download && make test-install-gotest && sudo make lint-install

      - name: Run test
        run: make test

      - name: Run lint
        run: make lint


